#!/bin/sh
# pathrelay install script
#
# Downloads the latest (or a specific) pathrelay release from GitHub,
# verifies its checksum, installs it to /usr/local/bin, and installs
# shell completion for the detected shell (bash/zsh/fish).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/forghani77/pathrelay/main/install.sh | sh
#   ./install.sh                     # latest release
#   ./install.sh v1.2.3              # specific release
#   PREFIX=$HOME/.local ./install.sh # custom install prefix
#
# Environment variables:
#   REPO        - GitHub repository as owner/name (default: forghani77/pathrelay)
#   PREFIX      - installation prefix (default: /usr/local)
#   FORCE_SHELL - force the shell for completion install (bash|zsh|fish)
#   RELEASE_URL - release download base URL
#                 (default: https://github.com/$REPO/releases/download)

set -eu

REPO="${REPO:-forghani77/pathrelay}"
PREFIX="${PREFIX:-/usr/local}"
RELEASE_URL="${RELEASE_URL:-https://github.com/$REPO/releases/download}"
BIN_DIR="$PREFIX/bin"

name="pathrelay"

# --- helpers ----------------------------------------------------------------

info() { printf '%s\n' "$*" >&2; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- detect platform ----------------------------------------------------------

OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
    Linux) os="linux" ;;
    Darwin) os="darwin" ;;
    *) fail "unsupported operating system: $OS (use 'go install' to build from source)" ;;
esac

case "$ARCH" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) fail "unsupported architecture: $ARCH" ;;
esac

# --- resolve download tool ----------------------------------------------------

if command -v curl >/dev/null 2>&1; then
    fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
    fetch() { wget -qO "$2" "$1"; }
else
    fail "curl or wget is required"
fi

# --- resolve version ----------------------------------------------------------

if [ $# -ge 1 ]; then
    VERSION="$1"
else
    info "Determining latest release..."
    VERSION="$(fetch "https://api.github.com/repos/$REPO/releases/latest" - | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p')"
    [ -n "$VERSION" ] || fail "could not determine the latest release; pass one explicitly, e.g. $0 v1.2.3"
fi

asset="$name-${os}-${arch}.tar.gz"
baseurl="$RELEASE_URL/$VERSION"

# --- download and verify --------------------------------------------------------

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
info "Downloading $name $VERSION ($os/$arch)..."
fetch "$baseurl/$asset" "$tmpdir/$asset"
fetch "$baseurl/checksums.txt" "$tmpdir/checksums.txt" || info "warning: checksums.txt not available, skipping verification"

if [ -f "$tmpdir/checksums.txt" ]; then
    want="$(sed -n "s/^\([0-9a-fA-F]*\)[[:space:]].*$asset$/\1/p" "$tmpdir/checksums.txt")"
    [ -n "$want" ] || fail "$asset not listed in checksums.txt"
    if command -v sha256sum >/dev/null 2>&1; then
        got="$(sha256sum "$tmpdir/$asset" | cut -d' ' -f1)"
    elif command -v shasum >/dev/null 2>&1; then
        got="$(shasum -a 256 "$tmpdir/$asset" | cut -d' ' -f1)"
    else
        info "warning: no sha256 tool found, skipping checksum verification"
        got="$want"
    fi
    [ "$got" = "$want" ] || fail "checksum mismatch for $asset: expected $want, got $got"
    info "Checksum OK"
fi

# --- install binary --------------------------------------------------------------

mkdir -p "$BIN_DIR"
tar -xzf "$tmpdir/$asset" -C "$tmpdir"
mv "$tmpdir/$name" "$BIN_DIR/$name"
chmod +x "$BIN_DIR/$name"

info "Installed $BIN_DIR/$name ($VERSION)"

# --- completions -----------------------------------------------------------------
#
# Completion scripts are generated by the freshly installed binary itself
# ("pathrelay completion <shell>") and installed for EVERY supported shell
# found on the system (bash, zsh, fish), so they work no matter which shell
# you end up in:
#
#   bash  - /etc/bash_completion.d when the bash-completion package is
#           installed; otherwise a guarded eval block in ~/.bashrc (plus a
#           .bash_profile source line so login shells pick it up too)
#   zsh   - a system site-functions dir when writable; otherwise a guarded
#           eval block in ~/.zshrc (works regardless of fpath/compinit setup)
#   fish  - ~/.config/fish/completions (picked up automatically)
#
# Set FORCE_SHELL=bash|zsh|fish to restrict installation to one shell.
# When run under sudo, rc files are edited for the invoking user, not root.

normalize_shell() {
    # "-/bin/bash" or "/usr/bin/fish.exe" -> "bash" / "fish" (POSIX-safe)
    b=${1##*/}
    b=${b#-}
    b=${b%.exe}
    b=${b%.sh}
    printf '%s\n' "$b"
}

detect_shell() {
    # 1. Explicit override
    if [ -n "${FORCE_SHELL:-}" ]; then
        normalize_shell "$FORCE_SHELL"
        return
    fi
    # 2. Login shell from the environment
    if [ -n "${SHELL:-}" ]; then
        normalize_shell "$SHELL"
        return
    fi
    # 3. The shell that invoked this script (parent process)
    if command -v ps >/dev/null 2>&1 && [ -n "${PPID:-}" ]; then
        comm="$(ps -p "$PPID" -o comm= 2>/dev/null | tr -d '[:space:]')"
        if [ -n "$comm" ]; then
            normalize_shell "$comm"
            return
        fi
    fi
    # 4. Login shell from the password database
    uid="$(id -u 2>/dev/null || true)"
    if [ -n "$uid" ] && command -v getent >/dev/null 2>&1; then
        sh="$(getent passwd "$uid" 2>/dev/null | cut -d: -f7)"
        if [ -n "$sh" ]; then
            normalize_shell "$sh"
            return
        fi
    fi
    user="${USER:-${LOGNAME:-}}"
    if [ -n "$user" ] && [ -r /etc/passwd ]; then
        sh="$(grep "^${user}:" /etc/passwd | cut -d: -f7 | tail -n1)"
        if [ -n "$sh" ]; then
            normalize_shell "$sh"
            return
        fi
    fi
    printf 'unknown'
}

is_usable_dir() {
    [ -d "$1" ] && { [ -w "$1" ] || [ "$(id -u 2>/dev/null || echo 0)" -eq 0 ]; }
}

# target_home prints the home directory of the user who should get rc edits:
# the sudo invoker when run as root via sudo, otherwise $HOME.
target_home() {
    if [ -n "${SUDO_USER:-}" ] && [ "$(id -u 2>/dev/null || echo 0)" -eq 0 ] && command -v getent >/dev/null 2>&1; then
        h="$(getent passwd "$SUDO_USER" 2>/dev/null | cut -d: -f6)"
        if [ -n "$h" ]; then
            printf '%s' "$h"
            return
        fi
    fi
    printf '%s' "${HOME:-}"
}

# ensure_rc_source_block appends an idempotent, guarded block that sources
# a completion file at shell startup. Shares the same markers as
# ensure_rc_block, so a given rc file only ever gets one of the two.
ensure_rc_source_block() {
    rc_file="$1"
    comp_file="$2"
    marker_begin="# >>> pathrelay completion >>>"

    if [ -f "$rc_file" ] && grep -qF "$marker_begin" "$rc_file"; then
        return
    fi
    {
        printf '\n%s\n' "$marker_begin"
        printf '# Added by pathrelay install.sh; safe to remove.\n'
        printf 'if [ -f %s ]; then\n' "'$comp_file'"
        printf '  . %s\n' "'$comp_file'"
        printf 'fi\n'
        printf '%s\n' "# <<< pathrelay completion <<<"
    } >> "$rc_file"
}

# ensure_rc_block appends an idempotent, guarded completion block to an rc
# file. The eval-based approach works regardless of fpath/compinit
# configuration and cleans itself up if the binary is removed.
ensure_rc_block() {
    rc_file="$1"
    shell_cmd="$2"
    marker_begin="# >>> pathrelay completion >>>"

    if [ -f "$rc_file" ] && grep -qF "$marker_begin" "$rc_file"; then
        return
    fi
    {
        printf '\n%s\n' "$marker_begin"
        printf '# Added by pathrelay install.sh; safe to remove.\n'
        printf 'if command -v pathrelay >/dev/null 2>&1; then\n'
        if [ "$shell_cmd" = bash ]; then
            # cobra V2 bash completion requires bash >= 4.4; skip silently on
            # ancient bash (e.g. macOS default 3.2) instead of erroring.
            printf '  if [ "${BASH_VERSINFO[0]:-0}" -ge 5 ] || { [ "${BASH_VERSINFO[0]:-0}" -eq 4 ] && [ "${BASH_VERSINFO[1]:-0}" -ge 4 ]; }; then\n'
            printf '    eval "$(pathrelay completion %s)"\n' "$shell_cmd"
            printf '  fi\n'
        else
            printf '  eval "$(pathrelay completion %s)"\n' "$shell_cmd"
        fi
        printf 'fi\n'
        printf '%s\n' "# <<< pathrelay completion <<<"
    } >> "$rc_file"
}

install_bash_completion() {
    home="$1"

    # System-wide install when the bash-completion package (or /etc hook)
    # exists and the dir is writable. The generated script needs bash >= 4.4.
    if { [ -r /usr/share/bash-completion/bash_completion ] || [ -r /etc/bash_completion ]; } \
       && is_usable_dir /etc/bash_completion.d; then
        if "$BIN_DIR/$name" completion bash 2>"$tmpdir/comp.err" > "/etc/bash_completion.d/$name"; then
            info "Installed bash completion: /etc/bash_completion.d/$name"
            # Wire it explicitly into the user's bashrc. The package loader
            # is lazy (loads on first TAB) and may not be sourced in every
            # setup; an explicit source line guarantees it always loads.
            ensure_rc_source_block "$home/.bashrc" "/etc/bash_completion.d/$name"
            info "Wired into $home/.bashrc (loads the system completion file)"
        else
            info "warning: failed to write /etc/bash_completion.d/$name: $(cat "$tmpdir/comp.err")"
        fi
    else
        # No bash-completion package: use an rc-file eval block instead.
        # Works on any bash >= 4.4; on ancient bash (macOS default 3.2) the
        # version guard in the block skips it instead of erroring.
        ensure_rc_block "$home/.bashrc" bash
        info "Added bash completion to $home/.bashrc"
    fi

    # Login shells read .bash_profile, not .bashrc — make sure it chains.
    prof="$home/.bash_profile"
    if [ ! -f "$prof" ]; then
        printf '[ -f ~/.bashrc ] && . ~/.bashrc\n' > "$prof"
        info "Created $prof (sources .bashrc)"
    elif ! grep -q '\.bashrc' "$prof"; then
        printf '\n# >>> pathrelay completion >>>\n[ -f ~/.bashrc ] && . ~/.bashrc\n# <<< pathrelay completion <<<\n' >> "$prof"
        info "Added .bashrc source line to $prof"
    fi
}

install_zsh_completion() {
    home="$1"

    for d in /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions; do
        if is_usable_dir "$d"; then
            if "$BIN_DIR/$name" completion zsh 2>"$tmpdir/comp.err" > "$d/_$name"; then
                info "Installed zsh completion: $d/_$name"
            else
                info "warning: failed to write $d/_$name: $(cat "$tmpdir/comp.err")"
                ensure_rc_block "$home/.zshrc" zsh
                info "Added zsh completion to $home/.zshrc"
            fi
            return
        fi
    done

    # No writable site-functions dir: eval block works regardless of
    # fpath/compinit configuration.
    ensure_rc_block "$home/.zshrc" zsh
    info "Added zsh completion to $home/.zshrc"
}

install_fish_completion() {
    home="$1"

    dest="${XDG_CONFIG_HOME:-$home/.config}/fish/completions/$name.fish"
    mkdir -p "$(dirname "$dest")"
    if "$BIN_DIR/$name" completion fish 2>"$tmpdir/comp.err" > "$dest"; then
        info "Installed fish completion: $dest"
    else
        rm -f "$dest"
        info "warning: failed to generate fish completion: $(cat "$tmpdir/comp.err")"
    fi
}

install_completions_all() {
    home="$(target_home)"
    current_shell="$(detect_shell)"
    info "Detected shell: ${current_shell}"

    # FORCE_SHELL restricts installation to a single shell.
    if [ -n "${FORCE_SHELL:-}" ]; then
        forced="$(normalize_shell "$FORCE_SHELL")"
        case "$forced" in
            bash|zsh|fish)
                "install_${forced}_completion" "$home"
                info "note: restart your shell (or: exec $forced) to activate completions"
                return
                ;;
            *)
                fail "FORCE_SHELL must be one of: bash, zsh, fish"
                ;;
        esac
    fi

    # Install for every supported shell present on the system, so completion
    # works no matter which shell the user actually ends up in.
    if command -v bash >/dev/null 2>&1; then
        install_bash_completion "$home"
    fi
    if command -v zsh >/dev/null 2>&1; then
        install_zsh_completion "$home"
    fi
    if command -v fish >/dev/null 2>&1; then
        install_fish_completion "$home"
    fi

    case "$current_shell" in
        bash|zsh|fish) ;;
        *)
            info "note: could not identify the current shell ('${current_shell:-}');"
            info "note: completions were installed for every shell found above"
            ;;
    esac
    info "note: restart your shell to activate completions"
}

install_completions_all

# --- done -------------------------------------------------------------------------

info "Run '$name --help' to get started, and 'sudo $name install' to set up"
info "the systemd service."

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) info "note: $BIN_DIR is not on your PATH" ;;
esac
