#!/bin/sh
# pathrelay install script
#
# Downloads the latest (or a specific) pathrelay release from GitHub,
# verifies its checksum, installs it to /usr/local/bin, and installs
# shell completion for the detected shell (bash/zsh/fish).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/forghani77/pathrelay/main/install.sh | sh
#   ./install.sh                     # latest release
#   ./install.sh v1.2.3              # specific release
#   PREFIX=$HOME/.local ./install.sh # custom install prefix
#
# Environment variables:
#   REPO        - GitHub repository as owner/name (default: forghani77/pathrelay)
#   PREFIX      - installation prefix (default: /usr/local)
#   FORCE_SHELL - force the shell for completion install (bash|zsh|fish)
#   RELEASE_URL - release download base URL
#                 (default: https://github.com/$REPO/releases/download)

set -eu

REPO="${REPO:-forghani77/pathrelay}"
PREFIX="${PREFIX:-/usr/local}"
RELEASE_URL="${RELEASE_URL:-https://github.com/$REPO/releases/download}"
BIN_DIR="$PREFIX/bin"

name="pathrelay"

# --- helpers ----------------------------------------------------------------

info() { printf '%s\n' "$*" >&2; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- detect platform ----------------------------------------------------------

OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
    Linux) os="linux" ;;
    Darwin) os="darwin" ;;
    *) fail "unsupported operating system: $OS (use 'go install' to build from source)" ;;
esac

case "$ARCH" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) fail "unsupported architecture: $ARCH" ;;
esac

# --- resolve download tool ----------------------------------------------------

if command -v curl >/dev/null 2>&1; then
    fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
    fetch() { wget -qO "$2" "$1"; }
else
    fail "curl or wget is required"
fi

# --- resolve version ----------------------------------------------------------

if [ $# -ge 1 ]; then
    VERSION="$1"
else
    info "Determining latest release..."
    VERSION="$(fetch "https://api.github.com/repos/$REPO/releases/latest" - | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p')"
    [ -n "$VERSION" ] || fail "could not determine the latest release; pass one explicitly, e.g. $0 v1.2.3"
fi

asset="$name-${os}-${arch}.tar.gz"
baseurl="$RELEASE_URL/$VERSION"

# --- download and verify --------------------------------------------------------

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
info "Downloading $name $VERSION ($os/$arch)..."
fetch "$baseurl/$asset" "$tmpdir/$asset"
fetch "$baseurl/checksums.txt" "$tmpdir/checksums.txt" || info "warning: checksums.txt not available, skipping verification"

if [ -f "$tmpdir/checksums.txt" ]; then
    want="$(sed -n "s/^\([0-9a-fA-F]*\)[[:space:]].*$asset$/\1/p" "$tmpdir/checksums.txt")"
    [ -n "$want" ] || fail "$asset not listed in checksums.txt"
    if command -v sha256sum >/dev/null 2>&1; then
        got="$(sha256sum "$tmpdir/$asset" | cut -d' ' -f1)"
    elif command -v shasum >/dev/null 2>&1; then
        got="$(shasum -a 256 "$tmpdir/$asset" | cut -d' ' -f1)"
    else
        info "warning: no sha256 tool found, skipping checksum verification"
        got="$want"
    fi
    [ "$got" = "$want" ] || fail "checksum mismatch for $asset: expected $want, got $got"
    info "Checksum OK"
fi

# --- install binary --------------------------------------------------------------

mkdir -p "$BIN_DIR"
tar -xzf "$tmpdir/$asset" -C "$tmpdir"
mv "$tmpdir/$name" "$BIN_DIR/$name"
chmod +x "$BIN_DIR/$name"

info "Installed $BIN_DIR/$name ($VERSION)"

# --- completions -----------------------------------------------------------------
#
# Completion scripts are generated by the freshly installed binary itself
# ("pathrelay completion <shell>"). Where they go:
#
#   bash  - /etc/bash_completion.d when the bash-completion package is
#           installed; otherwise a guarded eval line in ~/.bashrc
#   zsh   - a system site-functions dir when writable; otherwise a guarded
#           eval line in ~/.zshrc (works regardless of fpath/compinit setup)
#   fish  - ~/.config/fish/completions (picked up automatically)
#
# When run under sudo, rc files are edited for the invoking user, not root.

normalize_shell() {
    # "-/bin/bash" or "/usr/bin/fish.exe" -> "bash" / "fish" (POSIX-safe)
    b=${1##*/}
    b=${b#-}
    b=${b%.exe}
    b=${b%.sh}
    printf '%s\n' "$b"
}

detect_shell() {
    # 1. Explicit override
    if [ -n "${FORCE_SHELL:-}" ]; then
        normalize_shell "$FORCE_SHELL"
        return
    fi
    # 2. Login shell from the environment
    if [ -n "${SHELL:-}" ]; then
        normalize_shell "$SHELL"
        return
    fi
    # 3. The shell that invoked this script (parent process)
    if command -v ps >/dev/null 2>&1 && [ -n "${PPID:-}" ]; then
        comm="$(ps -p "$PPID" -o comm= 2>/dev/null | tr -d '[:space:]')"
        if [ -n "$comm" ]; then
            normalize_shell "$comm"
            return
        fi
    fi
    # 4. Login shell from the password database
    uid="$(id -u 2>/dev/null || true)"
    if [ -n "$uid" ] && command -v getent >/dev/null 2>&1; then
        sh="$(getent passwd "$uid" 2>/dev/null | cut -d: -f7)"
        if [ -n "$sh" ]; then
            normalize_shell "$sh"
            return
        fi
    fi
    user="${USER:-${LOGNAME:-}}"
    if [ -n "$user" ] && [ -r /etc/passwd ]; then
        sh="$(grep "^${user}:" /etc/passwd | cut -d: -f7 | tail -n1)"
        if [ -n "$sh" ]; then
            normalize_shell "$sh"
            return
        fi
    fi
    printf 'unknown'
}

is_usable_dir() {
    [ -d "$1" ] && { [ -w "$1" ] || [ "$(id -u 2>/dev/null || echo 0)" -eq 0 ]; }
}

# target_home prints the home directory of the user who should get rc edits:
# the sudo invoker when run as root via sudo, otherwise $HOME.
target_home() {
    if [ -n "${SUDO_USER:-}" ] && [ "$(id -u 2>/dev/null || echo 0)" -eq 0 ] && command -v getent >/dev/null 2>&1; then
        h="$(getent passwd "$SUDO_USER" 2>/dev/null | cut -d: -f6)"
        if [ -n "$h" ]; then
            printf '%s' "$h"
            return
        fi
    fi
    printf '%s' "${HOME:-}"
}

# ensure_rc_block appends an idempotent, guarded completion block to an rc
# file. The eval-based approach works regardless of fpath/compinit
# configuration and cleans itself up if the binary is removed.
ensure_rc_block() {
    rc_file="$1"
    shell_cmd="$2"
    marker_begin="# >>> pathrelay completion >>>"

    if [ -f "$rc_file" ] && grep -qF "$marker_begin" "$rc_file"; then
        return
    fi
    {
        printf '\n%s\n' "$marker_begin"
        printf '# Added by pathrelay install.sh; safe to remove.\n'
        printf 'if command -v pathrelay >/dev/null 2>&1; then\n'
        printf '  eval "$(pathrelay completion %s)"\n' "$shell_cmd"
        printf 'fi\n'
        printf '%s\n' "# <<< pathrelay completion <<<"
    } >> "$rc_file"
}

install_completion() {
    shell_name="$1"
    home="$(target_home)"

    case "$shell_name" in
        bash)
            if [ -r /usr/share/bash-completion/bash_completion ] || [ -r /etc/bash_completion ]; then
                if is_usable_dir /etc/bash_completion.d; then
                    dest="/etc/bash_completion.d/pathrelay"
                    if "$BIN_DIR/$name" completion bash > "$dest" 2>"$tmpdir/comp.err"; then
                        info "Installed bash completion: $dest"
                    else
                        info "warning: failed to write $dest: $(cat "$tmpdir/comp.err")"
                    fi
                    return
                fi
            fi
            ensure_rc_block "$home/.bashrc" "bash"
            info "Added bash completion to $home/.bashrc"
            ;;
        zsh)
            for d in /usr/local/share/zsh/site-functions /usr/share/zsh/site-functions; do
                if is_usable_dir "$d"; then
                    dest="$d/_pathrelay"
                    if "$BIN_DIR/$name" completion zsh > "$dest" 2>"$tmpdir/comp.err"; then
                        info "Installed zsh completion: $dest"
                    else
                        info "warning: failed to write $dest: $(cat "$tmpdir/comp.err")"
                    fi
                    return
                fi
            done
            ensure_rc_block "$home/.zshrc" "zsh"
            info "Added zsh completion to $home/.zshrc"
            ;;
        fish)
            dest="${XDG_CONFIG_HOME:-$home/.config}/fish/completions/pathrelay.fish"
            mkdir -p "$(dirname "$dest")"
            if "$BIN_DIR/$name" completion fish > "$dest" 2>"$tmpdir/comp.err"; then
                info "Installed fish completion: $dest"
            else
                rm -f "$dest"
                info "warning: failed to generate fish completion: $(cat "$tmpdir/comp.err")"
            fi
            ;;
    esac
    info "note: restart your shell (or: exec $shell_name) to activate completions"
}

current_shell="$(detect_shell)"
info "Detected shell: ${current_shell}"
case "$current_shell" in
    bash|zsh|fish)
        install_completion "$current_shell"
        ;;
    *)
        info "note: unsupported or unknown shell '${current_shell:-}', skipping completion install"
        info "note: you can force one with FORCE_SHELL=bash|zsh|fish and re-run"
        ;;
esac

# --- done -------------------------------------------------------------------------

info "Run '$name --help' to get started, and 'sudo $name install' to set up"
info "the systemd service."

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) info "note: $BIN_DIR is not on your PATH" ;;
esac
